print()
print("|-----------INPUT DATA------------|")
print()
a=int(input("Enter The Value Of A : "))
b=int(input("Enter The Value Of B : "))
c=int(input("Enter The Value Of C : "))
name = input("Enter Your Name     : ")
height = float(input("Enter Your Height   :"))
Valid_to_Vote=bool(input("Enter Validity (True or False) : "))
print("|---------------------------------|")
print(f"Value of A is    : {a}")
print(f"Value of B is    : {b}")
print(f"Value of C is    : {c}")
print(f"Entered Name     : {name}")
print(f"Entered height   : {height}")
print(f"Vote Eligibility : {Valid_to_Vote}")
print("|---------------------------------|")

print()
print("|------Arithematic Operator-------|")
print()
print(f"Addition of {a} , {b} and {c}       : {a+b+c}")
print(f"Subtraction of {a} , {b} and {c}    : {a-b-c}")
print(f"Multiplication of {a} , {b} and {c} : {a*b*c}")
print(f"Exponent of {a} and {b}             : {a**b}")
print(f"Division of {a} and {b}             : {a/b}")
print(f"Floor Division {b} and {c}          : {b//c}")
print(f"Modulus Division of {a} and {c}     : {a%c}")
print()
print("|---------------------------------|")

print()
print("|-------Relational Operator-------|")
print()
if(a==b):
    print(f"Value of {a} is equal to {b}")
if(a!=b):
    print(f"Value of {a} is not equal to {b}")
if(a>b):
    print(f"Value of {a} is greater than to {b}")
if(a<b):
    print(f"Value of {a} is lesser than to {b}")
if(a>=b):
    print(f"Value of {a} is greater than equal to {b}")
if(a<=b):
    print(f"Value of {a} is lesser than equal to {b}") 
print()
print("|---------------------------------|")
print()
print("|---------Logical Operator--------|")
print()
print(f"Logical AND Operation on {a} and {b} : {a and b}")
print(f"Logical OR Operation on {a} and {b}  : {a or b}")
bool_value=False
print(f"Logical NOT Operaton on Boolean Value ({bool_value}) : {not bool_value}")
print()
print("|---------------------------------|")